version: '3'
services:
  db:
    image: postgres:12
    container_name: 'airbnb_postgres'
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DB}
    ports:
      - '54320:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  test-db:
    image: postgres:12
    container_name: 'test_airbnb_postgres'
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${TEST_PSQL_USER}
      - POSTGRES_PASSWORD=${TEST_PSQL_PASSWORD}
      - POSTGRES_DB=${TEST_PSQL_DB}
    ports:
      - '54321:5432'
  app:
    container_name: 'airbnb_app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    restart: always
    volumes:
      - ./airbnb:/airbnb:Z
    env_file:
      - .env
    depends_on:
      - db
      - test-db
    command: python app.py
  migrate:
    container_name: 'airbnb_migrate'
    build:
      context: .
      dockerfile: ./migrate/Dockerfile
    volumes:
      - ./migrate:/migrate:Z
    env_file:
      - .env

volumes:
  postgres-data:
    driver: local
