version: '3'
services:
  db:
    image: postgres:12
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=pakhan
      - POSTGRES_PASSWORD=pakhan
      - POSTGRES_DB=airbnb
    ports:
      - '54320:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
